version: '3.7'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  api:
    image: ez-coins-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database